server {
    listen 80;

    server_name home.local;

    location / {
        proxy_pass http://react:80;
    }
}

server {
    listen 80;

    server_name api.home.local;

    location / {
        proxy_pass http://laravel:9000;
    }
}

server {
    listen 80;

    server_name ai.home.local;

    location / {
        proxy_pass http://fastapi:8000;
    }
}
