services:

  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: portfolio_api
      MARIADB_USER: portfolio
      MARIADB_PASSWORD: Aa##1234

    ports:
      - "3307:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - home-network

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - home-network

  fastapi:
    build:
      context: ../docker/fastapi

    container_name: fastapi

    restart: unless-stopped

    ports:
      - "8001:8000"

    networks:
      - home-network

networks:
  home-network:


volumes:
  mariadb_data:
  redis_data:
