name: ${PROJECT_NAME:-homeserver}-dev

services:

  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    restart: unless-stopped

    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE:-portfolio_api}
      MARIADB_USER: ${MYSQL_USER:-portfolio}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD must be set in compose/.env.example}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD must be set in compose/.env.example}

    ports:
      - "${MYSQL_PORT:-3307}:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - home-network

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "${REDIS_PORT:-6379}:6379"

    volumes:
      - redis_data:/data

    networks:
      - home-network

  fastapi:
    build:
      context: ../../apps/ai-service

    container_name: fastapi

    restart: unless-stopped

    ports:
      - "${FASTAPI_PORT:-8001}:8000"

    networks:
      - home-network

  laravel:
    build:
      context: ../../apps/portfolio-api

    container_name: laravel

    restart: unless-stopped

    working_dir: /var/www

    volumes:
      - ../../apps/portfolio-api:/var/www

    networks:
      - home-network

    depends_on:
      - mariadb

  nginx:
    image: nginx:alpine
    container_name: nginx

    restart: unless-stopped

    ports:
      - "${DEV_NGINX_PORT:-8080}:80"

    volumes:
      - ../../docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - fastapi

    networks:
      - home-network

networks:
  home-network:


volumes:
  mariadb_data:
  redis_data:
