name: HomeServer CI

on:
  push:
    branches:
      - main
      - sprint-*

  pull_request:
    branches:
      - main

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Compose env file
        run: cp compose/.env.example compose/.env

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build FastAPI
        run: docker build -t fastapi ./apps/ai-service

      - name: Build React
        run: docker build -t react ./apps/portfolio-web

      - name: Build Laravel
        run: docker build -t laravel ./apps/portfolio-api
