name: HomeServer CI

on:
  push:
    branches:
      - main
      - sprint-*

  pull_request:
    branches:
      - main

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose -f compose/docker-compose.yml config

      - name: Build FastAPI
        run: docker build -t fastapi ./docker/fastapi

      - name: Build React
        run: docker build -t react /srv/apps/portfolio-web

      - name: Build Laravel
        run: docker build -t laravel /srv/apps/portfolio-api
